Update spec.yml for project layers
raster-foundry/raster-foundry-api-spec pull request #86
Opened 2019-02-08 16:17 UTC by alkamin

## Overview

This PR updates the spec to include the implemented portions of the layer API that weren't already in the spec. It also removes some unused definitions.

2019-02-18 17:24 UTC, Lknechtli requested changes

2019-02-18 17:24 UTC, Lknechtli commented on spec/spec.yml
> +            colorGroup:
this should be colorGroupHex

2019-02-18 17:24 UTC, Lknechtli commented on spec/spec.yml
> +      properties:
looks like on the API these properties are actually at the same nesting level as the geometry field. This looks more correct, but we should probably reflect the current state of things in the spec, and make a new issue / pr to change it to being a proper geojson return

2019-02-18 17:24 UTC, Lknechtli commented on spec/spec.yml
> +            smartLayer:
smartLayerId

2019-02-18 17:24 UTC, Lknechtli commented on spec/spec.yml
> -  Point:
if you're going to remove these, you should also remove them from the enum in Geometry. I'd probably keep them since they're still a part of the spec though, and if we decide to use them then we'll need to paste them back in.

2019-02-18 17:24 UTC, Lknechtli commented on spec/spec.yml
> +        - $ref: '#/parameters/accepted'
this isn't currently a parameter, so we should either remove it or make an issue to add it to the API

2019-02-18 17:24 UTC, Lknechtli commented on spec/spec.yml
> +            $ref: '#/definitions/ScenePaginated'
This endpoint has additional / removed properties (see Scene.ProjectScene case class)
Since we currently use "Scene" for creating scenes / returning them individually, I think we need a third datamodel on the api, making it Scene, SceneBrowse, and SceneOrdered (or something... I think sceneOrder is the main difference though)

2019-02-18 17:24 UTC, Lknechtli commented on spec/spec.yml
> +    name: colorGroup
colorGroupHex

2019-02-18 17:24 UTC, Lknechtli commented on spec/spec.yml
> +    name: ordering
I don't think we've implemented these yet?

2019-02-20 19:38 UTC, alkamin commented on spec/spec.yml
> +        - $ref: '#/parameters/accepted'
We did actually add this as a param: https://github.com/raster-foundry/raster-foundry/blob/develop/app-backend/api/src/main/scala/project/QueryParameters.scala#L12-L18

2019-02-21 13:38 UTC, alkamin commented on spec/spec.yml
> -  Point:
I disagree about this one. The enum is just indicating the possible values for the `type` property (which is a string). These object definitions aren't actually referenced anywhere.

2019-02-21 13:52 UTC, alkamin commented on spec/spec.yml
> +            $ref: '#/definitions/ScenePaginated'
Yeah, it's had `images` removed  and `sceneOrder` added. Good catch!

2019-02-21 15:48 UTC, Lknechtli commented on spec/spec.yml
> -  Point:
hmm :thinking: weird. Ok then.

2019-02-21 22:00 UTC, Lknechtli approved these changes
Missed this, but otherwise lgtm

2019-02-21 22:00 UTC, Lknechtli commented on spec/spec.yml
> +    name: colorGroup
Still needs to be addressed, you fixed it in the other place but not here.

2019-02-22 04:09 UTC, alkamin commented on spec/spec.yml
> +    name: colorGroup
🤦‍♂️

2019-02-26 21:51 UTC, merged