Update scene browse params for #4615
raster-foundry/raster-foundry-api-spec pull request #87
Opened 2019-02-11 18:43 UTC by Lknechtli

## Overview
Update params for https://github.com/raster-foundry/raster-foundry/pull/4615
### Checklist

- [ ] Description of PR is in an appropriate section of the [changelog](https://github.com/raster-foundry/raster-foundry-api-spec/blob/develop/CHANGELOG.md) and grouped with similar changes if possible

2019-02-18 17:26 UTC, Lknechtli commented
just a note that squashing and merging has no conflicts

2019-03-06 13:30 UTC, notthatbreezy requested changes
I think `layer` needs to be removed

2019-03-06 13:30 UTC, notthatbreezy commented on spec/spec.yml
> +  layer:
Is this used anywhere? I don't see it added to an endpoint in this PR. If it is used, the name should be changed from `project` to `layer` I think.

2019-03-07 21:59 UTC, notthatbreezy approved these changes

2019-03-07 22:03 UTC, merged